spring:
  application:
    name: auth-service
  security:
    oauth2:
      client:
        registration:
          spring-boot-client:
            client-id: spring-boot-client
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: ""
            provider: keycloak
        provider:
          keycloak:
            token-uri: http://localhost:8081/realms/spring-app/protocol/openid-connect/token


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/