server:
  port: 8082

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: hr-service
          uri: lb://HR-SERVICE
          predicates:
            - Path=/api/employees/**
        - id: mission-service
          uri: lb://MISSION-SERVICE
          predicates:
            - Path=/api/missions/**
        - id: message-router
          uri: lb://MESSAGE-ROUTER
          predicates:
            - Path=/api/messages/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka