server:
  port: 8084

spring:
  application:
    name: MISSION-SERVICE

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://procurement-lighting-eagle-colleges.trycloudflare.com/realms/spring-app
          jwk-set-uri: http://host.docker.internal:8081/realms/spring-app/protocol/openid-connect/certs

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:h2:mem:missiondb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/