server:
  port: 8083

spring:
  application:
    name: hr-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/spring-app
          jwk-set-uri: http://localhost:8081/realms/spring-app/protocol/openid-connect/certs

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankapp}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:bankapp}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: hr_schema

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: hr_schema
    liquibase-schema: hr_schema

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

keycloak:
  admin:
    base-url: ${KEYCLOAK_ADMIN_BASE_URL:http://localhost:8081}
    realm: ${KEYCLOAK_ADMIN_REALM:spring-app}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:bankapp-admin}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:}
